spring:
  profiles:
    active: spring.profiles.active@
  security:
   oauth2:
    client:
      # From OIDC app
      clientId: {clientId}
      clientSecret: {clientSecret}
      # From Authorization Server's metadata
      accessTokenUri: https://{yourOktaDomain}/oauth2/default/v1/token
      userAuthorizationUri: https://{yourOktaDomain}/oauth2/default/v1/authorize
      clientAuthenticationScheme: form
      scope: openid profile email
    resource:
      # from your Auth Server's metadata, check .well-known/openid-configuration if not in .well-known/oauth-authorization-server
      userInfoUri: https://{yourOktaDomain}/oauth2/default/v1/userinfo